### ISSUE TITLE
main.py CORS issue

### ISSUE THREAD

**Issue by Dahye02** [LeeJaeJun-A/Sdev-WhiteHatASM#2]
https://github.com/LeeJaeJun-A/Sdev-WhiteHatASM/blob/edb4aa4a37e66f44c08a9624a9321d8e405fcd4f/backend/main.py#L28

```
app.add_middleware(
    CORSMiddleware,
    allow_origins=[origins],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)
``` 

I've noticed that docker uploading sometimes fails to login, and it seems that the CORS policy for "**allow_origins=[origins]**" has a list within a list, which sometimes causes the error.
Is it okay to modify "**allow_origins=origins**" like this?

docker upload할 때 가끔씩 로그인이 되지 않는 현상이 일어나 확인해보니, "**allow_origins=[origins]**" 해당 CORS정책에서 리스트 안에 리스트가 들어가 가끔 오류가 발생하는 것 같습니다.
"**allow_origins=origins**" 이런식으로 수정해도 괜찮을까요?

**Comment by LeeJaeJun-A** [comment]
네엡
